
  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."UPDATE_ACCOUNT" 
(
  NEW_NOME IN VARCHAR2,
  NEW_COGNOME IN VARCHAR2,
  NEW_PASSWORD IN VARCHAR2, 
  NEW_SIGLAR IN VARCHAR2, 
  NEW_SIGLAG IN VARCHAR2, 
  NEW_USERNAME IN VARCHAR2
) AS 
BEGIN
    update GRUPPO_AZZURRO.account set sigla_giornalista=NEW_SIGLAG, sigla_redazione =NEW_SIGLAR, password=NEW_PASSWORD, nome=NEW_NOME, cognome=NEW_COGNOME
    where username=NEW_USERNAME;
  
END UPDATE_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."UPDATE_ACCOUNT_NOPASS" 
 
(
  NEW_NOME IN VARCHAR2,
  NEW_COGNOME IN VARCHAR2,
  NEW_SIGLAR IN VARCHAR2, 
  NEW_SIGLAG IN VARCHAR2, 
  NEW_USERNAME IN VARCHAR2
) AS 
BEGIN
    update GRUPPO_AZZURRO.account set sigla_giornalista=NEW_SIGLAG, sigla_redazione =NEW_SIGLAR, nome=NEW_NOME, cognome=NEW_COGNOME
    where username=NEW_USERNAME;
  
END UPDATE_ACCOUNT_NOPASS;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."DELETE_GR_ACC_FROM_USER" 
(
   USERNAME_A IN VARCHAR2  
) AS 
BEGIN
 
  DELETE FROM GRUPPO_AZZURRO.ACCOUNT_GRUPPO   
where username=USERNAME_A;
commit;
END DELETE_GR_ACC_FROM_USER;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."SET_RUOLO_ACCOUNT" 
(
  RIF_USER IN VARCHAR2  
, RIF_GRUPPO IN VARCHAR2  
) AS 
BEGIN
  INSERT INTO GRUPPO_AZZURRO.ACCOUNT_GRUPPO VALUES (RIF_USER,RIF_GRUPPO);
  COMMIT;
END SET_RUOLO_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."VERIFICA_ACCOUNT" 
(
  STATO_A OUT integer
, USERNAME_A IN VARCHAR2  
) AS 
BEGIN
  
  select count(*) INTO STATO_A FROM GRUPPO_AZZURRO.ACCOUNT WHERE USERNAME = USERNAME_A AND STATO='A';
  
END VERIFICA_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."DELETE_ACCOUNT" 
(
  NEW_STATO IN VARCHAR2 , 
 USERNAME_A IN VARCHAR2  
) AS 
BEGIN
 
  update GRUPPO_AZZURRO.account set stato=NEW_STATO  
where username=USERNAME_A;
delete  from gruppo_azzurro.account_gruppo where username=USERNAME_A;
commit;
END DELETE_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GET_ACCOUNT_GRUPPI" 
(
  USERNAME_A IN VARCHAR2    
,    N_cursor in out SYS_REFCURSOR)

AS 
       begin
        open N_cursor for
          select AG.nome_gruppo

          from GRUPPO_AZZURRO.account_gruppo AG where AG.username=USERNAME_A;

END GET_ACCOUNT_GRUPPI;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GET_FUNZIONALITA_GRUPPO" 
(    N_cursor in out SYS_REFCURSOR
, GRUPPO_A in VARCHAR2)

AS 
BEGIN
  open N_cursor for

          select distinct  F.NOME_FUNZIONALITA, F.SIGLA_FUNZIONALITA 

          from FUNZIONALITA F, GRUPPO_FUNZIONALITA GF 
          WHERE GF.NOME_GRUPPO = GRUPPO_A AND F.SIGLA_FUNZIONALITA = GF.SIGLA_FUNZIONALITA ;
       
END GET_FUNZIONALITA_GRUPPO;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GET_LISTA_ACCOUNT" (

    N_cursor in out SYS_REFCURSOR)
    AS 
BEGIN
        open N_cursor for

          select nome, cognome,username, password, sigla_redazione,sigla_giornalista,stato

          from GRUPPO_AZZURRO.account where stato='A'  order by cognome,nome;

  
END GET_LISTA_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GET_LISTA_GRUPPI" 
(

    N_cursor in out SYS_REFCURSOR)

AS 
       begin
        open N_cursor for

          select nome_gruppo

          from GRUPPO_AZZURRO.gruppo;
END GET_LISTA_GRUPPI;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GETACCOUNTCURSOR" (
	   i_username IN ACCOUNT.USERNAME%TYPE,
     i_password IN ACCOUNT.PASSWORD%TYPE,
	   o_dbaccount OUT SYS_REFCURSOR)
IS
BEGIN
 
  OPEN o_dbaccount FOR
  SELECT * FROM ACCOUNT WHERE USERNAME = i_username AND PASSWORD = i_password AND STATO='A';
 
END;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."INSERIMENTO_ACCOUNT" 
(
  NEW_NOME IN VARCHAR2  
, NEW_COGNOME IN VARCHAR2  
, NEW_USERNAME IN VARCHAR2  
, NEW_PASSWORD IN VARCHAR2  
, NEW_SIGLAR IN VARCHAR2  
, NEW_SIGLAG IN VARCHAR2  
) AS 
BEGIN
  INSERT INTO GRUPPO_AZZURRO.ACCOUNT(nome, cognome, username, password, sigla_redazione,sigla_giornalista) values (NEW_NOME, NEW_COGNOME, NEW_USERNAME, NEW_PASSWORD , NEW_SIGLAR,NEW_SIGLAG);
  COMMIT;
END INSERIMENTO_ACCOUNT;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."INSERT_ACCOUNT_GRUPPI" 
(
  NEW_USER IN VARCHAR2  
, NEW_GRUPPO IN VARCHAR2  
) AS 
BEGIN
  INSERT INTO GRUPPO_AZZURRO.ACCOUNT_GRUPPO(username, nome_gruppo) values (NEW_USER, NEW_GRUPPO);
  COMMIT;

END INSERT_ACCOUNT_GRUPPI;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."GETACCOUNT_FROM_USER" (
	   i_username IN ACCOUNT.USERNAME%TYPE,
     
	   o_dbaccount OUT SYS_REFCURSOR)
IS
BEGIN
 
  OPEN o_dbaccount FOR
  SELECT * FROM ACCOUNT WHERE USERNAME = i_username;
 
END;
/
 

  CREATE OR REPLACE PROCEDURE "GRUPPO_AZZURRO"."VERIFICA_ACCOUNT" 
(
  STATO OUT integer
, USERNAME_A IN VARCHAR2 
) AS 
BEGIN
  
  select count(*) INTO STATO FROM GRUPPO_AZZURRO.ACCOUNT WHERE USERNAME = USERNAME_A;
  
END VERIFICA_ACCOUNT;
/
create or replace
PROCEDURE                  "VERIFICA_SIGLA" 
(
  STATO OUT integer
, SIGLA_GIORNALISTA_A IN VARCHAR2
) AS 
BEGIN
  
  select count(*) INTO STATO FROM GRUPPO_AZZURRO.ACCOUNT WHERE SIGLA_GIORNALISTA = SIGLA_GIORNALISTA_A;
  
END VERIFICA_SIGLA;

